apiVersion: v1
kind: Service
metadata:
  name: gowebserver-service
spec:
  selector:
    app: gowebserver
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gowebserver-deployment
spec:
  selector:
    matchLabels:
      app: gowebserver
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: gowebserver
    spec:
      containers:
      - name: gowebserver
        image: ghcr.io/dthuilot/gowebserver/gowebserver:v0.06
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: 512Mi
            cpu: "1"
          requests:
            memory: 256Mi
            cpu: "0.2"